import java.awt.Component;
import javax.swing.JOptionPane;

public class SetupContacts extends javax.swing.JFrame {

    String[] careGivers = new String[5];
    int addCount = 0;
    
    /**
     * Creates new form SetupContacts
     */
    public SetupContacts() {
        initComponents();
        setExtendedState(start.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userContactsLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameText = new javax.swing.JTextPane();
        phoneLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        phoneNumberString = new javax.swing.JTextPane();
        cellLabel = new javax.swing.JLabel();
        cellProviderDrop = new javax.swing.JComboBox<String>();
        relationLabel = new javax.swing.JLabel();
        relationDrop = new javax.swing.JComboBox<String>();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        moveUp = new javax.swing.JButton();
        moveDown = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactList = new javax.swing.JList<String>();
        previous = new javax.swing.JButton();
        finish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 480));

        userContactsLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        userContactsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userContactsLabel.setText("User Contacts");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name:");

        nameText.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jScrollPane1.setViewportView(nameText);

        phoneLabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        phoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phoneLabel.setText("Phone Number:");

        phoneNumberString.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jScrollPane3.setViewportView(phoneNumberString);

        cellLabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        cellLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cellLabel.setText("Cell Provider:");

        cellProviderDrop.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        cellProviderDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AT&T", "T-Mobile", "Sprint", "Verizon", "Nextel", "Virgin Mobile", "Cingular", "MetroPCS", "Cricket Wireless" }));

        relationLabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        relationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        relationLabel.setText("Relation:");

        relationDrop.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        relationDrop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spouse", "Sibling", "Friend", "Child", "Relative", "Parent" }));

        add.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        add.setText("Add");
        add.setActionCommand("Previous");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        moveUp.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        moveUp.setText("Move Up");
        moveUp.setActionCommand("Move Up ^");
        moveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveUpActionPerformed(evt);
            }
        });

        moveDown.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        moveDown.setText("Move Down");
        moveDown.setActionCommand("Move Up ^");
        moveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveDownActionPerformed(evt);
            }
        });

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        contactList.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contactList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(contactList);

        previous.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });

        finish.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        finish.setText("Finish");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phoneLabel)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cellLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(relationLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(relationDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cellProviderDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(userContactsLabel)
                                .addGap(294, 294, 294))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(edit)
                        .addGap(48, 48, 48)
                        .addComponent(moveUp)
                        .addGap(31, 31, 31)
                        .addComponent(moveDown)))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(userContactsLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cellLabel)
                            .addComponent(cellProviderDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(relationLabel)
                            .addComponent(relationDrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(edit)
                    .addComponent(moveUp)
                    .addComponent(moveDown))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finish, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(previous, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Object selectedItem = cellProviderDrop.getSelectedItem(); 
        String cellCarrier = selectedItem.toString();
        String phoneNum = phoneNumberString.getText();
        String smsGateway = "";

        cellCarrier = cellCarrier.toLowerCase();
        switch(cellCarrier) {
            case "at&t":
            smsGateway = "@txt.att.net";
            break;
            case "t-mobile":
            smsGateway = "@tmomail.net";
            break;
            case "sprint":
            smsGateway = "@messaging.sprintcs.com";
            break;
            case "verizon":
            smsGateway = "@vtext.com";
            break;
            case "nextel":
            smsGateway = "@messaging.nextel.com";
            break;
            case "virgin mobile":
            smsGateway = "@vmobl.com";
            break;
            case "cingular":
            smsGateway = "@cingularme.com";
            break;
            case "metropcs":
            smsGateway = "@mymetropcs.com";
            break;
            case "cricket wireless":
            smsGateway = "@sms.mycricket.com";
            break;
        };

        careGivers[addCount] = phoneNum + smsGateway;

        addCount = addCount + 1;
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
    }//GEN-LAST:event_editActionPerformed

    private void moveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveUpActionPerformed
    }//GEN-LAST:event_moveUpActionPerformed

    private void moveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveDownActionPerformed
    }//GEN-LAST:event_moveDownActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
    }//GEN-LAST:event_previousActionPerformed

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        Component frame = null;
            JOptionPane.showMessageDialog(frame,
    "Great! setup has been completed");
           this.setVisible(false);
        new ControlPanelUser().setVisible(true);
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetupContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetupContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetupContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetupContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetupContacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JLabel cellLabel;
    private javax.swing.JComboBox<String> cellProviderDrop;
    private javax.swing.JList<String> contactList;
    private javax.swing.JButton edit;
    private javax.swing.JButton finish;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton moveDown;
    private javax.swing.JButton moveUp;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextPane nameText;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextPane phoneNumberString;
    private javax.swing.JButton previous;
    private javax.swing.JComboBox<String> relationDrop;
    private javax.swing.JLabel relationLabel;
    private javax.swing.JLabel userContactsLabel;
    // End of variables declaration//GEN-END:variables
}
