
import java.awt.Font;
import java.io.File;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;

public class UserFallData extends javax.swing.JFrame {

    /**
     * Creates new form UserFallData
     */
    public UserFallData() {
        initComponents();
        fallDataTable.setModel(start.model); //set the fall data table to the model setup in start as a global var
        fallDataTable.setFont(new Font("Tahoma", Font.BOLD, 18));
        setExtendedState(start.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fallDataLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fallDataTable = new javax.swing.JTable();
        MainMenu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fallDataLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        fallDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fallDataLabel.setText("Fall Data");

        fallDataTable.setBorder(new javax.swing.border.MatteBorder(null));
        fallDataTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fallDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Time", "Date", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        fallDataTable.setToolTipText("HEllo");
        fallDataTable.getTableHeader().setReorderingAllowed(false);
        fallDataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fallDataTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fallDataTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(fallDataTable);
        if (fallDataTable.getColumnModel().getColumnCount() > 0) {
            fallDataTable.getColumnModel().getColumn(0).setHeaderValue("Time");
            fallDataTable.getColumnModel().getColumn(1).setHeaderValue("Date");
            fallDataTable.getColumnModel().getColumn(2).setHeaderValue("Contact");
        }

        MainMenu1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        MainMenu1.setText("Main Menu");
        MainMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(fallDataLabel)
                .addGap(312, 312, 312))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(fallDataLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fallDataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fallDataTableMouseClicked
    }//GEN-LAST:event_fallDataTableMouseClicked

    private void fallDataTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fallDataTableMousePressed
    }//GEN-LAST:event_fallDataTableMousePressed

    private void MainMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenu1ActionPerformed
        
           this.setVisible(false);
        new ControlPanelUser().setVisible(true);
    }//GEN-LAST:event_MainMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFallData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFallData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFallData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFallData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFallData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu1;
    private javax.swing.JLabel fallDataLabel;
    private javax.swing.JTable fallDataTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
